<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_68d29388ca08d',
	'title' => 'Flexible Content',
	'fields' => array(
		array(
			'key' => 'field_68d29389b8304',
			'label' => 'Flexible Content',
			'name' => 'flexible_content',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'hide_field' => '',
			'hide_label' => '',
			'hide_instructions' => '',
			'hide_required' => '',
			'acfe_flexible_advanced' => 1,
			'acfe_flexible_stylised_button' => 1,
			'acfe_flexible_layouts_templates' => 1,
			'acfe_flexible_layouts_previews' => 1,
			'acfe_flexible_layouts_previews_iframe' => 1,
			'acfe_flexible_layouts_previews_responsive' => 1,
			'acfe_flexible_layouts_thumbnails' => 0,
			'acfe_flexible_layouts_settings' => 0,
			'acfe_flexible_layouts_locations' => 0,
			'acfe_flexible_async' => array(
			),
			'acfe_flexible_add_actions' => array(
				0 => 'copy',
				1 => 'close',
			),
			'acfe_flexible_remove_button' => array(
			),
			'acfe_flexible_layouts_state' => 'user',
			'acfe_flexible_modal_edit' => array(
				'acfe_flexible_modal_edit_enabled' => '0',
				'acfe_flexible_modal_edit_size' => 'large',
			),
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => '0',
				'acfe_flexible_modal_title' => false,
				'acfe_flexible_modal_size' => 'full',
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => false,
			),
			'acfe_flexible_grid' => array(
				'acfe_flexible_grid_enabled' => '0',
				'acfe_flexible_grid_align' => 'center',
				'acfe_flexible_grid_valign' => 'stretch',
				'acfe_flexible_grid_wrap' => false,
			),
			'layouts' => array(
				'layout_68d29395b00f6' => array(
					'key' => 'layout_68d29395b00f6',
					'name' => 'slider',
					'label' => 'Slider',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68d294021b87d',
							'label' => 'Slides',
							'name' => 'slides',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_repeater_stylised_button' => 1,
							'layout' => 'block',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_68d294191b87e',
									'label' => 'Title',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68d294021b87d',
								),
								array(
									'key' => 'field_68d294201b87f',
									'label' => 'Description',
									'name' => 'description',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'acfe_textarea_code' => 0,
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_68d294021b87d',
								),
								array(
									'key' => 'field_68d2a4684680e',
									'label' => 'Image',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'uploader' => '',
									'return_format' => 'array',
									'library' => 'all',
									'acfe_thumbnail' => 0,
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'upload_folder' => '',
									'parent_repeater' => 'field_68d294021b87d',
								),
								array(
									'key' => 'field_68d2a4804680f',
									'label' => 'Has Button?',
									'name' => 'has_button',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'style' => '',
									'parent_repeater' => 'field_68d294021b87d',
								),
								array(
									'key' => 'field_68d2a4ae46810',
									'label' => 'Button Type',
									'name' => 'button_type',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_68d2a4804680f',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'primary' => 'Primary',
										'outline' => 'Outline',
										'ghost' => 'Ghost',
									),
									'default_value' => false,
									'return_format' => 'value',
									'multiple' => 0,
									'allow_null' => 0,
									'allow_in_bindings' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'create_options' => 0,
									'save_options' => 0,
									'allow_custom' => 0,
									'search_placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'parent_repeater' => 'field_68d294021b87d',
								),
								array(
									'key' => 'field_68d2a51146812',
									'label' => 'Button Link',
									'name' => 'button_link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_68d2a4804680f',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'allow_in_bindings' => 0,
									'parent_repeater' => 'field_68d294021b87d',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => 'flexible.php',
					'acfe_flexible_render_style' => '',
					'acfe_flexible_render_script' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_layout_locations' => array(
					),
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
					'acfe_layout_col' => 'auto',
					'acfe_layout_allowed_col' => false,
				),
				'layout_68d2aac4b6d59' => array(
					'key' => 'layout_68d2aac4b6d59',
					'name' => 'taxonomy',
					'label' => 'Taxonomy',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68d2aadb44849',
							'label' => 'Select a Taxonomy',
							'name' => 'taxonomy',
							'aria-label' => '',
							'type' => 'acfe_taxonomies',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'hide_field' => '',
							'hide_label' => '',
							'hide_instructions' => '',
							'hide_required' => '',
							'admin_column_enabled' => 0,
							'taxonomy' => array(
								0 => 'category',
								1 => 'post_tag',
								2 => 'product_cat',
								3 => 'product_tag',
								4 => 'product_occasion',
								5 => 'product_season',
								6 => 'product_audience',
							),
							'field_type' => 'select',
							'max' => '',
							'default_value' => array(
							),
							'return_format' => 'object',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
							'instruction_placement' => '',
							'acfe_permissions' => '',
							'allow_in_bindings' => 0,
							'choices' => array(
							),
							'ajax' => 0,
							'placeholder' => '',
							'search_placeholder' => '',
							'layout' => '',
							'toggle' => 0,
							'allow_custom' => 0,
							'other_choice' => 0,
							'min' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => 'flexible.php',
					'acfe_flexible_render_style' => '',
					'acfe_flexible_render_script' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_layout_locations' => array(
					),
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
					'acfe_layout_col' => 'auto',
					'acfe_layout_allowed_col' => false,
				),
				'layout_68d3a0390b085' => array(
					'key' => 'layout_68d3a0390b085',
					'name' => 'post_type',
					'label' => 'Post Type',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68d3a38b73401',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_68d3a03f0b088',
							'label' => 'Select a Post Type',
							'name' => 'post_type',
							'aria-label' => '',
							'type' => 'acfe_post_types',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'post',
								1 => 'product',
							),
							'field_type' => 'select',
							'default_value' => array(
							),
							'return_format' => 'object',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'allow_in_bindings' => 0,
							'choices' => array(
							),
							'ajax' => 0,
							'placeholder' => '',
							'search_placeholder' => '',
							'layout' => '',
							'toggle' => 0,
							'allow_custom' => 0,
							'other_choice' => 0,
							'min' => '',
							'max' => '',
						),
						array(
							'key' => 'field_68d3ce4af7b58',
							'label' => 'Max Posts',
							'name' => 'max_posts',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 12,
							'min' => '',
							'max' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_68d3d2cff290b',
							'label' => 'Order By',
							'name' => 'order_by',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_68d3a311733ff',
										'operator' => '!=',
										'value' => '1',
									),
								),
								array(
									array(
										'field' => 'field_68d3a21b733fc',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'date' => 'Date',
								'title' => 'Title',
								'rand' => 'Random',
								'relevance' => 'Relevance',
								'none' => 'None',
							),
							'default_value' => 'date',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
							'allow_custom' => 0,
							'search_placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
						),
						array(
							'key' => 'field_68d3d327f290c',
							'label' => 'Order',
							'name' => 'order',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_68d3a311733ff',
										'operator' => '!=',
										'value' => '1',
									),
								),
								array(
									array(
										'field' => 'field_68d3a21b733fc',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'ASC' => 'Ascending',
								'DESC' => 'Descending',
							),
							'default_value' => 'DESC',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
							'allow_custom' => 0,
							'search_placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
						),
						array(
							'key' => 'field_68d3a1da733fb',
							'label' => 'Product Filters',
							'name' => 'product_filters',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_68d3a03f0b088',
										'operator' => '==',
										'value' => 'product',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'acfe_seamless_style' => 0,
							'acfe_group_modal' => 0,
							'sub_fields' => array(
								array(
									'key' => 'field_68d3a2d3733fe',
									'label' => 'On Sale?',
									'name' => 'on_sale',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Display only the products that are on sale',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'style' => '',
								),
								array(
									'key' => 'field_68d3a35373400',
									'label' => 'Featured?',
									'name' => 'featured',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Display only the products marked as featured',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'style' => '',
								),
								array(
									'key' => 'field_68d3a21b733fc',
									'label' => 'Best Sellers?',
									'name' => 'best_sellers',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Display only the best selling products',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'style' => '',
								),
								array(
									'key' => 'field_68d3a311733ff',
									'label' => 'Is New?',
									'name' => 'is_new',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Display only the new products (last 30 days)',
									'default_value' => 0,
									'allow_in_bindings' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'style' => '',
								),
								array(
									'key' => 'field_68d3a251733fd',
									'label' => 'Product Taxonomies',
									'name' => 'product_taxonomies',
									'aria-label' => '',
									'type' => 'acfe_taxonomies',
									'instructions' => 'Display only the the products in the selected taxonomies',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'instruction_placement' => '',
									'hide_field' => '',
									'hide_label' => '',
									'hide_instructions' => '',
									'hide_required' => '',
									'admin_column_enabled' => 0,
									'taxonomy' => array(
										0 => 'product_cat',
										1 => 'product_tag',
										2 => 'product_occasion',
										3 => 'product_season',
										4 => 'product_audience',
									),
									'field_type' => 'checkbox',
									'default_value' => array(
									),
									'return_format' => 'object',
									'layout' => 'vertical',
									'toggle' => 0,
									'allow_custom' => 0,
									'min' => '',
									'max' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'allow_in_bindings' => 0,
									'multiple' => 0,
									'allow_null' => 0,
									'choices' => array(
									),
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'search_placeholder' => '',
									'other_choice' => 0,
								),
								array(
									'key' => 'field_68d3a4a53888e',
									'label' => 'Category Terms',
									'name' => 'category_terms',
									'aria-label' => '',
									'type' => 'acfe_taxonomy_terms',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_68d3a251733fd',
												'operator' => '==contains',
												'value' => 'product_cat',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'taxonomy' => array(
										0 => 'product_cat',
									),
									'allow_terms' => '',
									'allow_level' => '',
									'field_type' => 'checkbox',
									'default_value' => array(
									),
									'return_format' => 'id',
									'layout' => 'vertical',
									'toggle' => 0,
									'save_terms' => 0,
									'load_terms' => 0,
									'allow_in_bindings' => 0,
									'choices' => array(
									),
									'ui' => 0,
									'multiple' => 0,
									'allow_null' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'search_placeholder' => '',
									'allow_custom' => 0,
									'other_choice' => 0,
									'min' => '',
									'max' => '',
								),
								array(
									'key' => 'field_68d3a4f73888f',
									'label' => 'Tag Terms',
									'name' => 'tag_terms',
									'aria-label' => '',
									'type' => 'acfe_taxonomy_terms',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_68d3a251733fd',
												'operator' => '==contains',
												'value' => 'product_tag',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'taxonomy' => array(
										0 => 'product_tag',
									),
									'allow_terms' => '',
									'allow_level' => '',
									'field_type' => 'checkbox',
									'default_value' => array(
									),
									'return_format' => 'id',
									'layout' => 'vertical',
									'toggle' => 0,
									'save_terms' => 0,
									'load_terms' => 0,
									'allow_in_bindings' => 0,
									'choices' => array(
									),
									'ui' => 0,
									'multiple' => 0,
									'allow_null' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'search_placeholder' => '',
									'allow_custom' => 0,
									'other_choice' => 0,
									'min' => '',
									'max' => '',
								),
								array(
									'key' => 'field_68d3a52338891',
									'label' => 'Occasion Terms',
									'name' => 'occasion_terms',
									'aria-label' => '',
									'type' => 'acfe_taxonomy_terms',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_68d3a251733fd',
												'operator' => '==contains',
												'value' => 'occasion',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'instruction_placement' => '',
									'hide_field' => '',
									'hide_label' => '',
									'hide_instructions' => '',
									'hide_required' => '',
									'admin_column_enabled' => 0,
									'taxonomy' => array(
										0 => 'product_occasion',
									),
									'allow_terms' => '',
									'allow_level' => '',
									'field_type' => 'checkbox',
									'default_value' => array(
									),
									'return_format' => 'id',
									'layout' => 'vertical',
									'toggle' => 0,
									'save_terms' => 0,
									'load_terms' => 0,
									'min' => '',
									'max' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'allow_in_bindings' => 0,
									'choices' => array(
									),
									'ui' => 0,
									'multiple' => 0,
									'allow_null' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'search_placeholder' => '',
									'allow_custom' => 0,
									'other_choice' => 0,
								),
								array(
									'key' => 'field_68d40c835adc0',
									'label' => 'Season Terms',
									'name' => 'season_terms',
									'aria-label' => '',
									'type' => 'acfe_taxonomy_terms',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_68d3a251733fd',
												'operator' => '==contains',
												'value' => 'season',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'instruction_placement' => '',
									'hide_field' => '',
									'hide_label' => '',
									'hide_instructions' => '',
									'hide_required' => '',
									'admin_column_enabled' => 0,
									'taxonomy' => array(
										0 => 'product_season',
									),
									'allow_terms' => '',
									'allow_level' => '',
									'field_type' => 'checkbox',
									'default_value' => array(
									),
									'return_format' => 'id',
									'layout' => 'vertical',
									'toggle' => 0,
									'save_terms' => 0,
									'load_terms' => 0,
									'min' => '',
									'max' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'allow_in_bindings' => 0,
									'choices' => array(
									),
									'ui' => 0,
									'multiple' => 0,
									'allow_null' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'search_placeholder' => '',
									'allow_custom' => 0,
									'other_choice' => 0,
								),
								array(
									'key' => 'field_68d46be1e2655',
									'label' => 'Audience Terms',
									'name' => 'audience_terms',
									'aria-label' => '',
									'type' => 'acfe_taxonomy_terms',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_68d3a251733fd',
												'operator' => '==contains',
												'value' => 'audience',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'instruction_placement' => '',
									'hide_field' => '',
									'hide_label' => '',
									'hide_instructions' => '',
									'hide_required' => '',
									'admin_column_enabled' => 0,
									'taxonomy' => array(
										0 => 'product_audience',
									),
									'allow_terms' => '',
									'allow_level' => '',
									'field_type' => 'checkbox',
									'default_value' => array(
									),
									'return_format' => 'id',
									'layout' => 'vertical',
									'toggle' => 0,
									'save_terms' => 0,
									'load_terms' => 0,
									'min' => '',
									'max' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'allow_in_bindings' => 0,
									'choices' => array(
									),
									'ui' => 0,
									'multiple' => 0,
									'allow_null' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'search_placeholder' => '',
									'allow_custom' => 0,
									'other_choice' => 0,
								),
							),
							'acfe_group_modal_close' => 0,
							'acfe_group_modal_button' => '',
							'acfe_group_modal_size' => 'large',
						),
						array(
							'key' => 'field_68d3a39973402',
							'label' => 'Show Shop All Button?',
							'name' => 'show_button',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_68d3a03f0b088',
										'operator' => '==',
										'value' => 'product',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'style' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => 'flexible.php',
					'acfe_flexible_render_style' => '',
					'acfe_flexible_render_script' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_layout_locations' => array(
					),
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
					'acfe_layout_col' => 'auto',
					'acfe_layout_allowed_col' => false,
				),
			),
			'acfe_settings' => '',
			'instruction_placement' => '',
			'acfe_permissions' => '',
			'min' => '',
			'max' => '',
			'button_label' => 'Add Section',
			'acfe_flexible_hide_empty_message' => false,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_layouts_placeholder' => false,
			'acfe_flexible_grid_container' => false,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'flexible.blade.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 1,
	'acfe_display_title' => '',
	'acfe_permissions' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1758753471,
));

endif;