<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_68c1e6647b2a6',
	'title' => 'Mega Menu',
	'fields' => array(
		array(
			'key' => 'field_68c6ecc8982e3',
			'label' => 'Is Sub Menu?',
			'name' => 'is_sub_menu',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Only tick this is the menu is a sub menu item',
			'default_value' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'style' => '',
		),
		array(
			'key' => 'field_68c6ee13e268e',
			'label' => 'Is Mega Menu?',
			'name' => 'is_mega_menu',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68c6ecc8982e3',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'style' => '',
		),
		array(
			'key' => 'field_68c1f95e61341',
			'label' => 'Is Button?',
			'name' => 'is_button',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68c6ecc8982e3',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'style' => '',
		),
		array(
			'key' => 'field_68c1ed1439219',
			'label' => 'Description',
			'name' => 'description',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'This only applies when the parent is a Mega Menu',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68c6ecc8982e3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_68c1e664473f4',
			'label' => 'Is Featured?',
			'name' => 'is_featured',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'This only applies when the parent is a Mega Menu',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68c6ecc8982e3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'style' => '',
		),
		array(
			'key' => 'field_68c1e6b7473f5',
			'label' => 'Image',
			'name' => 'image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'This only applies when the parent is a Mega Menu',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68c6ecc8982e3',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_68c1e664473f4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'array',
			'library' => 'all',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
			'upload_folder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'nav_menu_item',
				'operator' => '==',
				'value' => 'location/primary_navigation',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 1,
	'acfe_display_title' => '',
	'acfe_permissions' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1758751077,
));

endif;